// Given a string, we have to find out all its subsequences of it. A String is a
// subsequence of a given String, that is generated by deleting some character of
// given string without changing its order.
// Input : abc
// Output : a, b, c, ab, bc, ac, abc.

#include<iostream>
#include<string>
using namespace std;

void subsequence(string s, int i, string cur){
    if(i == s.size()){
        if(cur != "") cout<< cur<<" ";
        return;
    }
    subsequence(s, i+1, cur);
    subsequence(s, i+1, cur+s[i]);
    
}

int main(){
    string s = "abc", cur;
    subsequence(s, 0, cur);
    return 0;
}